name: CI with Gradle - Test and Build

# Trigger the workflow pull request,
# but only for the main branch
on:
  pull_request:
    branches: [ main ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dorg.gradle.jvmargs="-Xmx5g -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'macos-11', 'ubuntu-latest', 'windows-latest' ]

    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Test (macos, jvm, js)
        uses: gradle/gradle-build-action@v2.8.0
        if: matrix.os == 'macos-11'
        with:
          arguments: --full-stacktrace build

      - name: Test (linux)
        uses: gradle/gradle-build-action@v2.8.0
        if: matrix.os == 'ubuntu-latest'
        with:
          arguments: --full-stacktrace linuxX64Test

      - name: Test (windows)
        uses: gradle/gradle-build-action@v2.8.0
        if: matrix.os == 'windows-latest'
        with:
          arguments: --full-stacktrace mingwX64Test

      - name: Upload reports
        uses: actions/upload-artifact@v3.1.2
        with:
          name: 'reports-${{ matrix.os }}'
          path: '**/build/reports/**'
