name: CI with Gradle - Test and Build

# Trigger the workflow pull request,
# but only for the main branch
on:
  pull_request:
    branches: [ main ]

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dorg.gradle.jvmargs="-Xmx5g -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ 'macos-latest', 'ubuntu-latest', 'windows-latest' ]

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Test (macos, jvm, js)
        if: matrix.os == 'macos-latest'
        run: ./gradlew build --full-stacktrace

      - name: Test (linux)
        if: matrix.os == 'ubuntu-latest'
        run: ./gradlew linuxX64Test --full-stacktrace

      - name: Test (windows)
        if: matrix.os == 'windows-latest'
        run: ./gradlew mingwX64Test --full-stacktrace

      - name: Upload reports
        uses: actions/upload-artifact@v4.4.3
        with:
          name: 'reports-${{ matrix.os }}'
          path: '**/build/reports/**'
